#use the golang base image
FROM golang:1.6
MAINTAINER Daniel van Gils

#get all the go testing stuff
RUN go get github.com/tools/godep
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega

#copy the source files
RUN mkdir -p /usr/local/go/src/github.com/shahriarb/starter
ADD . /usr/local/go/src/github.com/shahriarb/starter

#switch to our app directory
WORKDIR /usr/local/go/src/github.com/shahriarb/starter